version: '3'
services:
  web:
    build: .
    ports:
      - 80:80
    environment:
      - RENDER_HOSTNAME=app-botwpp-site
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database